export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_SELECTED_IMAGE = "SET_SELECTED_IMAGE";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const SET_SELECTED_PRODUCT_SIZE = "SET_SELECTED_PRODUCT_SIZE";
export const SET_SELECTED_PRODUCT_QUANTITY = "SET_SELECTED_PRODUCT_QUANTITY";
