export const SHOW_SIGN_IN = "SHOW_SIGN_IN";
export const SHOW_SIGN_UP = "SHOW_SIGN_UP";
export const SHOW_RECOVER_PASSWORD = "SHOW_RECOVER_PASSWORD";
export const SET_SELECTED_MENU_ITEM = "SET_SELECTED_MENU_ITEM";
