export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_LASTNAME = 'SET_USER_LASTNAME';
